import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const flow = readFileSync('public/kp/kp-flow-v2.js', 'utf8');
const flowGuard = readFileSync('public/kp/kp-flow-guard-v2.js', 'utf8');
const css = readFileSync('public/kp/kp-flow-v2.css', 'utf8');
const renderer = readFileSync('public/kp/kp-ux-v12.js', 'utf8');
const worker = readFileSync('src/demo-worker-v19-kp-flow.js', 'utf8');
const kpWorker = readFileSync('src/demo-worker-v20-mobile-fixes.js', 'utf8');
const releaseWorker = readFileSync('src/demo-worker-v38-staff.js', 'utf8');
const menuWorker = readFileSync('src/demo-worker-v39-admin-menu.js', 'utf8');
const diagnosticWorker = readFileSync('src/demo-worker-v40-admin-diagnostic.js', 'utf8');
const staffEntry = readFileSync('src/demo-worker-v41-house-cleaning-staff.js', 'utf8');
const defectRpc = readFileSync('src/client-defect-rpc.js', 'utf8');
const sharedBooking = readFileSync('src/demo-worker-v50-shared-booking.js', 'utf8');
const clientExperience = readFileSync('src/demo-worker-v53-client-experience.js', 'utf8');
const publicOrder = readFileSync('src/production-public-order.js', 'utf8');
const wrangler = readFileSync('wrangler.jsonc', 'utf8');

for (const label of ['Данные', 'Услуги', 'Условия', 'Проверка']) assert.ok(flow.includes(label), `flow must contain step ${label}`);
assert.ok(flow.includes('data-progress-step="4"'), 'flow must have the fourth progress step');
assert.ok(!flow.includes('data-progress-step="5"'), 'flow must not introduce a fifth step');
assert.ok(flow.includes("document.getElementById('addItemBtn')?.classList.add('kp-flow-legacy-hidden')"), 'legacy add-service button must be hidden');
assert.ok(flow.includes('Из списка') && flow.includes('Своя услуга'), 'service modes must exist');
assert.ok(flow.includes('Добавить в КП'), 'single primary add action must be named Add to KP');
for (const unit of ['м²', 'шт.', 'усл. ед.', 'Другое']) assert.ok(flow.includes(unit), `quick unit ${unit} must exist`);
assert.ok(flow.includes('guessUnit'), 'automatic unit suggestion must exist');
assert.ok(flow.includes('unitTouched'), 'manual unit choice must have priority over automatic suggestion');
assert.ok(flow.includes('Редактировать существующую') && flow.includes('Добавить отдельной строкой'), 'duplicate control must stay explicit');
assert.ok(flow.includes("fields.prepayment_percent.value = '0'"), 'repeat payment click must be able to reset to zero');
assert.ok(renderer.includes('Number(quote.prepayment_percent || 0) > 0'), 'PDF payment row must be conditional');
assert.ok(renderer.includes("? [['Условия оплаты:'"), 'payment row must render only when payment exists');
assert.ok(flowGuard.includes('KP_PDF_CANCELLED'), 'cancelled native PDF share must be detected');
assert.ok(flowGuard.includes('state.currentId && state.lastSaved?.id === state.currentId'), 'cancelled PDF share must preserve the current quote state');
assert.ok(worker.includes("const USED_PREFIX = 'kp:outgoing-used:v3:'"), 'permanent used-number ledger must exist');
assert.ok(worker.includes("const RESET_MARKER = 'kp:outgoing-reset-to-15:first5-v1'"), 'number guard must preserve start-at-15 marker');
assert.ok(worker.includes("url.pathname === '/kp/delete'"), 'delete flow must reserve the old outgoing number');
assert.ok(worker.includes('sequence <= highWater'), 'historically deleted numbers below high-water must be blocked');
assert.ok(worker.includes('raiseCounterTo'), 'counter must only move forward');
assert.ok(worker.includes('sequence === currentSequence'), 'editing an existing KP must retain its own number');
assert.ok(worker.includes("./demo-worker-v18-client.js"), 'numbering worker must preserve client worker as its base');
assert.ok(kpWorker.includes("./demo-worker-v19-kp-flow.js"), 'KP worker must preserve hardened numbering worker');
assert.ok(releaseWorker.includes("./demo-worker-v37-booking-resilience.js"), 'staff worker must preserve release chain');
assert.ok(menuWorker.includes("./demo-worker-v38-staff.js"), 'admin menu wrapper must preserve staff/release chain');
assert.ok(diagnosticWorker.includes("./demo-worker-v39-admin-menu.js"), 'diagnostic wrapper must preserve admin menu chain');
assert.ok(staffEntry.includes("./demo-worker-v40-admin-diagnostic.js"), 'HOUSE CLEANING STAFF wrapper must preserve diagnostic chain');
assert.ok(wrangler.includes('src/production-public-order.js'), 'wrangler must point to the public-order production entry');
assert.ok(publicOrder.includes("./demo-worker-v53-client-experience.js"), 'public-order entry must preserve release 53');
assert.ok(clientExperience.includes("./demo-worker-v50-shared-booking.js"), 'release 53 must preserve shared booking');
assert.ok(sharedBooking.includes("./client-defect-rpc.js"), 'shared booking must preserve defect RPC');
assert.ok(defectRpc.includes("./demo-worker-v44-production.js"), 'defect RPC wrapper must preserve the complete client/KP production chain');
assert.ok(!css.includes('visualViewport'), 'flow CSS must not depend on visualViewport');
assert.ok(!/\b(?:html|body)\s*\{[^}]*overflow\s*:\s*hidden/i.test(css), 'flow CSS must not lock page scrolling');
assert.ok(!/document\.body\.style\.overflow|document\.documentElement\.style\.overflow/.test(flow), 'flow JS must not lock page scrolling');

console.log('KP flow contract checks passed');
